apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-ascended
spec:
  containers:
  - name: nginx-pod-ascended-container
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
