apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ascended
spec:
  containers:
  - name: redis-storage-ascended
    image: redis:alpine
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: redis-storage
    emptyDir: {}