apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: alpha
      image: nginx
      env:
        - name: container1
          value: alpha
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
    - name: beta
      image: busybox
      command: ["sleep", "4800"]
      env:
        - name: container2
          value: beta
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"