apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  template:
    spec:
      containers:
      - command:
        - echo
        - Hello I am from job
        image: busybox
        name: hello-job
        resources: {}
      restartPolicy: Never
