apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
    - name: CONFIG_MAP_TEST
      valueFrom:
        configMapKeyRef:
          name: keyvalcfgmap
          key: config.txt