apiVersion: v1
kind: Namespace
metadata:
  name: finance-ascended
---
apiVersion: v1
kind: Pod
metadata:
  name: temp-bus
  namespace: finance-ascended
spec:
  containers:
  - name: temp-bus
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"